### ISSUE TITLE
in #denied-dupes it shows &amp; instead of just '&'

### ISSUE THREAD

**Issue by Tarek1337** [SteamingMutt/DiscordFeedback#113]
As the title says, In #denied-dupes it will show &amp: instead of just '&'

Idk if it's something fixable or not.

![image](https://user-images.githubusercontent.com/13603398/29741679-f8c0e59e-8a71-11e7-875b-0bf7168ffaab.png)

**Comment by SteamingMutt** [comment]
This is due to the admin queue embeds not passing through a http entities
translator, it's absolutely fixable but extremely low priority.

Op 26 aug. 2017 15:19 schreef "Tarek1337" <notifications@github.com>:

As the title says, In #denied-dupes it will show &amp: instead of just '&'

Idk if it's something fixable or not.

[image: image]
<https://user-images.githubusercontent.com/13603398/29741679-f8c0e59e-8a71-11e7-875b-0bf7168ffaab.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SteamingMutt/DiscordFeedback/issues/113>, or mute the
thread
